version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot-challenge:/opt/certbot-challenge
      #del- /etc/letsencrypt/live/metrics.languagetransfer.org/fullchain.pem:/opt/metrics.pem
      #del- /etc/letsencrypt/live/metrics.languagetransfer.org/privkey.pem:/opt/metrics-key.pem
      #del- /etc/letsencrypt/live/downloads.languagetransfer.org/fullchain.pem:/opt/downloads.pem
      #del- /etc/letsencrypt/live/downloads.languagetransfer.org/privkey.pem:/opt/downloads-key.pem
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./secrets:/opt/secrets
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    environment:
      MONGO_INITDB_DATABASE: lt_logged_data
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /opt/secrets/mongo_root_password
      MONGO_INITDB_USERNAME: lt_db_user
      MONGO_INITDB_PASSWORD_FILE: /opt/secrets/mongo_password
    ports:
      - 127.0.0.1:27017:27017
  metrics:
    image: metrics
    restart: always
    volumes:
      - ./secrets:/opt/secrets
    ports:
      - 127.0.0.1:6774:6774
